### PR TITLE
Simplify and fix DynamicBlockVector

### LINKED ISSUE #524: Crashing simulations
I am running with 6*40 processes

- [job_0.json.txt](https://github.com/hpsint/hpsint/files/11176786/job_0.json.txt) [job_0.cmd.txt](https://github.com/hpsint/hpsint/files/11176783/job_0.cmd.txt) [job_0.out.txt](https://github.com/hpsint/hpsint/files/11176802/job_0.out.txt)
- [job_1.json.txt](https://github.com/hpsint/hpsint/files/11176785/job_1.json.txt) [job_1.cmd.txt](https://github.com/hpsint/hpsint/files/11176782/job_1.cmd.txt) [job_1.out.txt](https://github.com/hpsint/hpsint/files/11176804/job_1.out.txt)
- [job_0.json.txt](https://github.com/hpsint/hpsint/files/11176786/job_0.json.txt) [job_2.cmd.txt](https://github.com/hpsint/hpsint/files/11176781/job_2.cmd.txt) [job_2.out.txt](https://github.com/hpsint/hpsint/files/11176805/job_2.out.txt)

and they are all crashing when GT and AMR are run:

Screenshot from 2023-04-07 09-05-56

The number of op increases by one. It looks like a memory issue. However, what is odd is that I could assemble the full system matrix and setup for that ILU and there I had no memory issues (I only run till 500s but the number of DoFs is still higher at that time).

After some testing, I identified that the code crashes in these parts (old vs. new remapping)

https://github.com/hpsint/hpsint/blob/657ee47702e0b0d512da1098df6945a2c159498b/include/pf-applications/grain_tracker/tracker.h#L888-L927

https://github.com/hpsint/hpsint/blob/657ee47702e0b0d512da1098df6945a2c159498b/include/pf-applications/grain_tracker/tracker.h#L442-L618

At these places no new global vectors are allocated...

@vovannikov Any ideas?

### PR DESCRIPTION
**Pull request by peterrum**
closes #524

### CODE REVIEW

File: include/pf-applications/lac/dynamic_block_vector.h [hunk 1]
```diff
@@ -400,13 +387,11 @@ namespace dealii
         void
         swap(DynamicBlockVector &V)
         {
-          std::swap(this->block_counter, V.block_counter);
           std::swap(this->blocks, V.blocks);
           std::swap(this->size_, V.size_);
         }
 
       private:
-        unsigned int                            block_counter;
```
Comment (peterrum) [inline include/pf-applications/lac/dynamic_block_vector.h:409]: I introduced `block_counter`, since I thought the system will be much more dynamic and we have to change the block size more frequently. But this is not the case...

File: include/pf-applications/lac/dynamic_block_vector.h [hunk 2]
```diff
@@ -70,22 +68,17 @@ namespace dealii
...
-          if (n_blocks() > old_blocks_size)
-            {
-              blocks.resize(n_blocks());
+          blocks.resize(n);
 
-              for (unsigned int b = old_blocks_size; b < n_blocks(); ++b)
-                {
-                  if (blocks[b] == nullptr)
-                    blocks[b] = std::make_shared<BlockType>();
+          for (unsigned int b = old_blocks_size; b < n_blocks(); ++b)
```
Comment (peterrum) [inline include/pf-applications/lac/dynamic_block_vector.h:75]: For some reason `old_blocks_size` was not correct (some inconsistency of `block_counter` and `blocks.size()`).

**Review by vovannikov — APPROVED** [review]
